/**
 * Art. 50 EU AI Act — Disclosure Compliance Detector v2
 *
 * Pure regex/string scanning on raw HTML — no external parsers.
 * Five criteria × 20 pts each = 100 pt total.
 *
 * Philosophy: expose the diagnosis (WHAT is wrong + WHY it matters legally).
 * The prescription (HOW to fix) is gated behind the paid product.
 */

export type CriterionKey =
  | "disclosure_present"
  | "disclosure_visible"
  | "machine_readable"
  | "language_match"
  | "synthetic_media";

export type Art50Signal = {
  criterion: CriterionKey;
  label: string;
  legalRef: string;
  detected: boolean;
  evidence?: string;         // snippet ≤100 chars that triggered detection
  score: number;
  maxScore: number;          // always 20
  severity: "critical" | "warning" | "ok";
  contextNote: string;       // WHY this matters legally — NOT how to fix it
};

export type Art50ScanResult = {
  url: string;
  score: number;
  grade: "A" | "B" | "C" | "D" | "F";
  gradeLabel: string;
  signals: Art50Signal[];
  criticalCount: number;
  warningCount: number;
  riskLevel: "alto" | "medio" | "basso";
  sanctionEstimate: string;
  scannedAt: string;
  disclaimer: string;
};

// ─── Helpers ─────────────────────────────────────────────────────────────────

function stripTags(html: string): string {
  return html.replace(/<[^>]+>/g, " ").replace(/\s+/g, " ");
}

function excerpt(text: string, max = 100): string {
  const t = text.replace(/\s+/g, " ").trim();
  return t.length <= max ? t : t.slice(0, max) + "…";
}

// ─── Individual checks ────────────────────────────────────────────────────────

function checkDisclosurePresent(html: string): Pick<Art50Signal, "detected" | "evidence" | "score" | "severity"> {
  const bodyText = stripTags(html).toLowerCase();

  const phrases = [
    "generato da intelligenza artificiale",
    "generato da ai",
    "ai-generated",
    "generated by ai",
    "powered by ai",
    "prodotto da ai",
    "contenuto generato automaticamente",
    "assistito da intelligenza artificiale",
  ];

  for (const phrase of phrases) {
    const idx = bodyText.indexOf(phrase);
    if (idx !== -1) {
      const raw = stripTags(html);
      const ev = excerpt(raw.slice(Math.max(0, idx - 8), idx + phrase.length + 40));
      return { detected: true, evidence: ev, score: 20, severity: "ok" };
    }
  }

  // meta generator
  const metaRe = /<meta[^>]+name=["']generator["'][^>]*content=["'][^"']*ai/i;
  if (metaRe.test(html)) {
    const m = html.match(metaRe);
    return { detected: true, evidence: excerpt(m![0]), score: 20, severity: "ok" };
  }

  return { detected: false, score: 0, severity: "critical" };
}

function checkDisclosureVisible(html: string): Pick<Art50Signal, "detected" | "evidence" | "score" | "severity"> {
  const terms = "generato da|ai-generated|powered by ai|intelligenza artificiale|assistito da ai";

  // Header
  if (new RegExp(`<header[^>]*>[\\s\\S]{0,3000}?(${terms})`, "i").test(html)) {
    return { detected: true, evidence: "Trovata nell'area <header>", score: 20, severity: "ok" };
  }
  // Nav
  if (new RegExp(`<nav[^>]*>[\\s\\S]{0,1500}?(${terms})`, "i").test(html)) {
    return { detected: true, evidence: "Trovata nell'area <nav>", score: 20, severity: "ok" };
  }
  // Within 1500 chars of <body> opening
  const bodyStart = html.indexOf("<body");
  if (bodyStart !== -1) {
    const near = html.slice(bodyStart, bodyStart + 1500).toLowerCase();
    if (new RegExp(terms, "i").test(near)) {
      return { detected: true, evidence: "Trovata nella zona iniziale della pagina", score: 20, severity: "ok" };
    }
  }
  // aria-label on dialog/aside/banner
  const ariaRe = /<(?:dialog|aside|section|div)[^>]*aria-label=["'][^"']*ai[^"']*["'][^>]*>/i;
  if (ariaRe.test(html)) {
    const m = html.match(ariaRe);
    return { detected: true, evidence: excerpt(m![0]), score: 20, severity: "ok" };
  }
  // Only in footer — not compliant
  if (new RegExp(`<footer[^>]*>[\\s\\S]{0,3000}?(${terms})`, "i").test(html)) {
    return {
      detected: false,
      evidence: "Disclosure rilevata solo nel <footer>",
      score: 0,
      severity: "critical",
    };
  }

  return { detected: false, score: 0, severity: "critical" };
}

function checkMachineReadable(
  html: string,
  headers: Record<string, string>
): Pick<Art50Signal, "detected" | "evidence" | "score" | "severity"> {
  if (headers["x-ai-disclosure"] || headers["x-ai-generated"]) {
    const val = headers["x-ai-disclosure"] ?? headers["x-ai-generated"];
    return { detected: true, evidence: `Header HTTP: X-AI-Disclosure: ${val}`, score: 20, severity: "ok" };
  }

  const metaRe = /<meta[^>]+name=["'](ai-generated|ai-disclosure)["'][^>]*>/i;
  if (metaRe.test(html)) {
    const m = html.match(metaRe);
    return { detected: true, evidence: excerpt(m![0]), score: 20, severity: "ok" };
  }

  const ldRe = /<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi;
  let ldM: RegExpExecArray | null;
  while ((ldM = ldRe.exec(html)) !== null) {
    const c = ldM[1].toLowerCase();
    if (c.includes('"@type"') && (c.includes("aicontentg") || c.includes("isaigenerated") || c.includes("automatedagent"))) {
      return { detected: true, evidence: `JSON-LD: ${excerpt(ldM[1], 60)}`, score: 20, severity: "ok" };
    }
  }

  return { detected: false, score: 0, severity: "warning" };
}

function checkLanguageMatch(html: string): Pick<Art50Signal, "detected" | "evidence" | "score" | "severity"> {
  const langM = html.match(/<html[^>]+lang=["']([a-zA-Z-]+)["']/i);
  const lang = langM ? langM[1].toLowerCase() : null;

  const hasIt = /intelligenza artificiale|generato da ai|assistito da ia/i.test(html);
  const hasEn = /ai-generated|generated by ai|powered by ai/i.test(html);
  const anyDisclosure = hasIt || hasEn;

  const evBase = `lang="${lang ?? "(non impostato)"}"`;

  if (!lang || lang.startsWith("en")) {
    return { detected: anyDisclosure, evidence: evBase, score: anyDisclosure ? 20 : 0, severity: anyDisclosure ? "ok" : "warning" };
  }
  if (lang.startsWith("it")) {
    if (hasIt) return { detected: true, evidence: `${evBase} — disclosure in italiano rilevata`, score: 20, severity: "ok" };
    if (hasEn) return { detected: false, evidence: `${evBase} — disclosure solo in inglese`, score: 0, severity: "warning" };
    return { detected: false, evidence: evBase, score: 0, severity: "warning" };
  }
  return { detected: anyDisclosure, evidence: `${evBase} — lingua non italiana`, score: anyDisclosure ? 20 : 0, severity: anyDisclosure ? "ok" : "warning" };
}

function checkSyntheticMedia(html: string): Pick<Art50Signal, "detected" | "evidence" | "score" | "severity"> {
  const aiTerms = /generated|synthetic|ai|fake|deepfake|artificiale/i;
  const mediaRe = /<(video|audio|img)[^>]*>/gi;
  const tags: { tag: string; type: string }[] = [];
  let m: RegExpExecArray | null;
  while ((m = mediaRe.exec(html)) !== null) tags.push({ tag: m[0], type: m[1] });

  if (tags.length === 0) {
    return { detected: true, evidence: "Nessun elemento media rilevato — criterio non applicabile", score: 20, severity: "ok" };
  }

  for (const { tag } of tags) {
    if (aiTerms.test(tag)) {
      return { detected: true, evidence: `Tag media etichettato: ${excerpt(tag, 60)}`, score: 20, severity: "ok" };
    }
  }

  // Check nearby text
  const nearRe = /<(?:video|audio|img)[^>]*>([\s\S]{0,200})/gi;
  let near: RegExpExecArray | null;
  while ((near = nearRe.exec(html)) !== null) {
    if (aiTerms.test(stripTags(near[1]))) {
      return { detected: true, evidence: `Etichettatura AI vicino al media: "${excerpt(stripTags(near[1]), 50)}"`, score: 20, severity: "ok" };
    }
  }

  // video without labeling = critical (deepfake risk)
  const hasVideo = tags.some(t => t.type === "video");
  return {
    detected: false,
    evidence: `${tags.length} elemento/i media senza etichettatura AI`,
    score: 0,
    severity: hasVideo ? "critical" : "warning",
  };
}

// ─── Grade ────────────────────────────────────────────────────────────────────

function gradeFromScore(score: number): "A" | "B" | "C" | "D" | "F" {
  if (score >= 90) return "A";
  if (score >= 70) return "B";
  if (score >= 50) return "C";
  if (score >= 30) return "D";
  return "F";
}

const GRADE_LABELS: Record<string, string> = {
  A: "Conforme",
  B: "Quasi conforme",
  C: "Parzialmente conforme",
  D: "Non conforme",
  F: "Gravemente non conforme",
};

// ─── Helpers ──────────────────────────────────────────────────────────────────

// Cap response body at maxBytes to prevent memory exhaustion
async function readBodyCapped(res: Response, maxBytes: number): Promise<string> {
  if (!res.body) return await res.text();
  const reader = res.body.getReader();
  const chunks: Uint8Array[] = [];
  let total = 0;
  while (true) {
    const { done, value } = await reader.read();
    if (done || !value) break;
    total += value.byteLength;
    if (total > maxBytes) {
      reader.cancel();
      break;
    }
    chunks.push(value);
  }
  const combined = new Uint8Array(total <= maxBytes ? total : maxBytes);
  let offset = 0;
  for (const chunk of chunks) {
    combined.set(chunk.subarray(0, Math.min(chunk.byteLength, maxBytes - offset)), offset);
    offset += chunk.byteLength;
    if (offset >= maxBytes) break;
  }
  return new TextDecoder().decode(combined);
}

// ─── Public API ───────────────────────────────────────────────────────────────

export async function scanUrl(url: string): Promise<Art50ScanResult> {
  let response = await fetch(url, {
    headers: { "User-Agent": "AIComply-Art50-Scanner/1.0" },
    signal: AbortSignal.timeout(8000),
    redirect: "manual",
  });

  // Follow at most one redirect, only to https://
  if (response.status >= 300 && response.status < 400) {
    const location = response.headers.get("location") ?? "";
    if (!location.startsWith("https://")) {
      throw new Error(`Redirect bloccato: destinazione non sicura`);
    }
    response = await fetch(location, {
      headers: { "User-Agent": "AIComply-Art50-Scanner/1.0" },
      signal: AbortSignal.timeout(8000),
      redirect: "manual",
    });
  }

  if (!response.ok) throw new Error(`HTTP ${response.status} — ${response.statusText}`);

  const headers: Record<string, string> = {};
  response.headers.forEach((v, k) => { headers[k.toLowerCase()] = v; });

  const html = await readBodyCapped(response, 2 * 1024 * 1024);

  const SIGNAL_DEFS: Array<{
    criterion: CriterionKey;
    label: string;
    legalRef: string;
    contextNote: string;
    check: Pick<Art50Signal, "detected" | "evidence" | "score" | "severity">;
  }> = [
    {
      criterion: "disclosure_present",
      label: "Disclosure AI presente",
      legalRef: "Art. 50(1) AI Act",
      contextNote:
        "L'Art. 50(1) impone che i sistemi AI a interazione diretta con persone fisiche rendano esplicita la natura artificiale del sistema. L'assenza di qualsiasi disclosure è considerata violazione diretta e non sanabile con misure tecniche minori.",
      check: checkDisclosurePresent(html),
    },
    {
      criterion: "disclosure_visible",
      label: "Disclosure in posizione prominente",
      legalRef: "Art. 50(1)(a) + Considerando 132 AI Act",
      contextNote:
        "Il Considerando 132 precisa che l'informazione deve essere fornita 'in modo tempestivo, chiaro e comprensibile', prima o al momento dell'interazione. Una disclosure collocata esclusivamente nel footer non soddisfa questo requisito secondo le linee guida interpretative della Commissione.",
      check: checkDisclosureVisible(html),
    },
    {
      criterion: "machine_readable",
      label: "Disclosure leggibile automaticamente",
      legalRef: "Art. 50(1) + Art. 13 AI Act",
      contextNote:
        "I requisiti di trasparenza dell'AI Act si estendono alla leggibilità automatizzata per consentire la sorveglianza del mercato da parte delle autorità nazionali competenti (Art. 74). L'assenza di metadati machine-readable può ostacolare le procedure di audit.",
      check: checkMachineReadable(html, headers),
    },
    {
      criterion: "language_match",
      label: "Dichiarazione nella lingua corretta",
      legalRef: "Art. 50(1) + considerazioni EDPB su accessibilità",
      contextNote:
        "La disclosure deve essere comprensibile per l'utente destinatario. Per siti rivolti a utenti italofoni, una disclosure esclusivamente in inglese è considerata insufficiente ai fini della comprensibilità effettiva richiesta dall'Art. 50.",
      check: checkLanguageMatch(html),
    },
    {
      criterion: "synthetic_media",
      label: "Media sintetici etichettati",
      legalRef: "Art. 50(4) AI Act",
      contextNote:
        "L'Art. 50(4) estende gli obblighi di disclosure ai contenuti multimediali generati o manipolati da AI (deepfake). I sistemi che producono o distribuiscono video, audio o immagini sintetiche sono soggetti a obblighi specifici distinti da quelli per i sistemi conversazionali.",
      check: checkSyntheticMedia(html),
    },
  ];

  const signals: Art50Signal[] = SIGNAL_DEFS.map(({ criterion, label, legalRef, contextNote, check }) => ({
    criterion,
    label,
    legalRef,
    contextNote,
    maxScore: 20,
    ...check,
  }));

  const score = signals.reduce((acc, s) => acc + s.score, 0);
  const grade = gradeFromScore(score);
  const criticalCount = signals.filter(s => s.severity === "critical").length;
  const warningCount  = signals.filter(s => s.severity === "warning").length;
  const riskLevel: Art50ScanResult["riskLevel"] =
    criticalCount >= 2 ? "alto" : criticalCount === 1 ? "medio" : "basso";

  return {
    url,
    score,
    grade,
    gradeLabel: GRADE_LABELS[grade],
    signals,
    criticalCount,
    warningCount,
    riskLevel,
    sanctionEstimate: "Fino all'1% del fatturato annuo globale (Art. 99(3) AI Act)",
    scannedAt: new Date().toISOString(),
    disclaimer:
      "Questo strumento è indicativo e non costituisce parere legale. La conformità all'Art. 50 richiede una valutazione completa da parte di un esperto qualificato. I risultati dipendono dall'HTML pubblicamente accessibile della pagina scansionata.",
  };
}
