"use client";

import { useState } from "react";
import {
  Stamp,
  MessageSquare,
  Archive,
  FileImage,
  Video,
  Music,
  FileText,
  Shield,
  Download,
  CheckCircle,
  X,
  Copy,
  AlertTriangle,
  Plus,
} from "lucide-react";
import { generateC2PAManifest, verifyC2PAManifest } from "@/lib/crypto/c2pa";
import { appendEvidence } from "@/lib/evidence/evidence-layer";
import { motion, AnimatePresence } from "framer-motion";

// ─── Persistence ──────────────────────────────────────────────────────────────

const ASSETS_KEY = "trust_labeler_assets";

type AssetType = "image" | "video" | "audio" | "text";

type AI_GENERATOR =
  | "ChatGPT / GPT-4o (OpenAI)"
  | "DALL-E 3 (OpenAI)"
  | "Midjourney v6"
  | "Stable Diffusion XL"
  | "Sora (OpenAI)"
  | "ElevenLabs (audio)"
  | "Gemini (Google)"
  | "Claude (Anthropic)"
  | "Modello interno"
  | "Altro";

type LabeledAsset = {
  id: string;
  name: string;
  type: AssetType;
  generator: AI_GENERATOR;
  modelId: string;
  labeledAt: string;
  manifest: ReturnType<typeof generateC2PAManifest>;
  verification: ReturnType<typeof verifyC2PAManifest>;
};

function loadAssets(): LabeledAsset[] {
  if (typeof window === "undefined") return [];
  const raw = localStorage.getItem(ASSETS_KEY);
  return raw ? JSON.parse(raw) : [];
}

function saveAssets(assets: LabeledAsset[]) {
  localStorage.setItem(ASSETS_KEY, JSON.stringify(assets));
}

// ─── Disclosure generator ─────────────────────────────────────────────────────

type DisclosureForm = {
  productName: string;
  useCase: string;
  language: "it" | "en";
  companyName: string;
  deepfake: boolean;
  emotionRecognition: boolean;
};

function generateDisclosureText(form: DisclosureForm): string {
  const useCaseLabels: Record<string, string> = {
    chatbot_customer_support: "assistenza clienti",
    chatbot_hr: "selezione del personale",
    chatbot_legal: "consulenza legale",
    chatbot_medical: "supporto medico",
    content_generation: "generazione di contenuti",
    recommendation: "raccomandazione personalizzata",
    deepfake: "produzione di contenuti sintetici",
    emotion_recognition: "analisi del comportamento",
  };

  const productName = form.productName || "questo sistema";
  const company = form.companyName || "la nostra azienda";
  const useCase = useCaseLabels[form.useCase] || form.useCase;

  if (form.language === "it") {
    let text = `INFORMATIVA AI — ART. 50 REG. UE 2024/1689\n\n`;
    text += `Stai interagendo con un sistema di intelligenza artificiale.\n\n`;
    text += `${company} utilizza "${productName}", un sistema AI per ${useCase}. `;
    text += `Ai sensi dell'art. 50(1) del Regolamento UE 2024/1689 (EU AI Act), `;
    text += `ti informiamo che le risposte che ricevi sono generate automaticamente `;
    text += `da un sistema di intelligenza artificiale e non da un operatore umano.\n\n`;
    text += `Hai sempre il diritto di richiedere di essere messo in contatto con `;
    text += `un operatore umano.\n\n`;
    if (form.deepfake) {
      text += `CONTENUTI SINTETICI (Art. 50(4)): I contenuti visivi, audio o testuali `;
      text += `prodotti da questo sistema sono generati artificialmente. `;
      text += `Non rappresentano persone, eventi o luoghi reali, salvo diversa indicazione.\n\n`;
    }
    if (form.emotionRecognition) {
      text += `ANALISI DATI PERSONALI (Art. 50(3)): Questo sistema può analizzare `;
      text += `espressioni facciali, tonalità vocale o altri segnali comportamentali `;
      text += `a scopo di ${useCase}. Hai il diritto di opporti a tale trattamento.\n\n`;
    }
    text += `Per informazioni: privacy@${company.toLowerCase().replace(/\s+/g, "")}.it`;
    return text;
  } else {
    let text = `AI DISCLOSURE — ART. 50 EU AI ACT (REG. EU 2024/1689)\n\n`;
    text += `You are interacting with an artificial intelligence system.\n\n`;
    text += `${company} uses "${productName}", an AI system for ${useCase}. `;
    text += `Pursuant to Art. 50(1) of EU Regulation 2024/1689 (EU AI Act), `;
    text += `we inform you that responses are automatically generated by an AI `;
    text += `system and not by a human operator.\n\n`;
    text += `You have the right to request to be connected to a human operator at any time.\n\n`;
    if (form.deepfake) {
      text += `SYNTHETIC CONTENT (Art. 50(4)): Visual, audio or textual content `;
      text += `produced by this system is artificially generated. `;
      text += `It does not represent real persons, events or places unless otherwise stated.\n\n`;
    }
    if (form.emotionRecognition) {
      text += `BEHAVIORAL DATA PROCESSING (Art. 50(3)): This system may analyze `;
      text += `facial expressions, vocal tone or other behavioral signals for `;
      text += `${useCase} purposes. You have the right to object to this processing.\n\n`;
    }
    text += `Contact: privacy@${company.toLowerCase().replace(/\s+/g, "")}.com`;
    return text;
  }
}

// ─── Asset type helpers ───────────────────────────────────────────────────────

const TYPE_ICON: Record<AssetType, React.FC<React.SVGProps<SVGSVGElement>>> = {
  image: FileImage,
  video: Video,
  audio: Music,
  text: FileText,
};

const TYPE_COLOR: Record<AssetType, string> = {
  image: "#6366f1",
  video: "#f59e0b",
  audio: "#10b981",
  text: "#0ea5e9",
};

const TYPE_LABEL: Record<AssetType, string> = {
  image: "Immagine",
  video: "Video",
  audio: "Audio",
  text: "Testo",
};

const AI_GENERATORS: AI_GENERATOR[] = [
  "ChatGPT / GPT-4o (OpenAI)",
  "DALL-E 3 (OpenAI)",
  "Midjourney v6",
  "Stable Diffusion XL",
  "Sora (OpenAI)",
  "ElevenLabs (audio)",
  "Gemini (Google)",
  "Claude (Anthropic)",
  "Modello interno",
  "Altro",
];

const INPUT_STYLE: React.CSSProperties = {
  width: "100%",
  padding: "7px 10px",
  borderRadius: "8px",
  border: "1px solid rgba(0,0,0,0.12)",
  fontSize: "13px",
  color: "#0D1016",
  background: "#fff",
  outline: "none",
};

// ─── Component ────────────────────────────────────────────────────────────────

export default function TrustLabelerPage() {
  const [tab, setTab] = useState<"watermark" | "disclosure" | "registry">("watermark");
  const [assets, setAssets] = useState<LabeledAsset[]>(() => loadAssets());
  const [selectedAsset, setSelectedAsset] = useState<LabeledAsset | null>(null);
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState({
    name: "",
    type: "image" as AssetType,
    generator: "ChatGPT / GPT-4o (OpenAI)" as AI_GENERATOR,
    modelId: "",
  });
  const [toast, setToast] = useState<string | null>(null);

  // Disclosure
  const [disclosureForm, setDisclosureForm] = useState<DisclosureForm>({
    productName: "",
    useCase: "chatbot_customer_support",
    language: "it",
    companyName: "",
    deepfake: false,
    emotionRecognition: false,
  });
  const [disclosureText, setDisclosureText] = useState<string | null>(null);

  function showToastMsg(msg: string) {
    setToast(msg);
    setTimeout(() => setToast(null), 3000);
  }

  // ── Watermark actions ───────────────────────────────────────────────────────

  function handleGenerateWatermark() {
    if (!form.name.trim() || !form.generator) return;
    const manifest = generateC2PAManifest(form.name, form.type, form.generator);
    const verification = verifyC2PAManifest(manifest);
    const newAsset: LabeledAsset = {
      id: crypto.randomUUID(),
      name: form.name,
      type: form.type,
      generator: form.generator,
      modelId: form.modelId,
      labeledAt: new Date().toISOString(),
      manifest,
      verification,
    };
    const updated = [newAsset, ...assets];
    setAssets(updated);
    saveAssets(updated);
    setSelectedAsset(newAsset);
    setShowForm(false);
    setForm({ name: "", type: "image", generator: "ChatGPT / GPT-4o (OpenAI)", modelId: "" });
    showToastMsg("✓ Watermark C2PA applicato");
    void appendEvidence(
      "log",
      {
        evento: `Watermark C2PA applicato: ${form.name}`,
        componente: "Trust-Labeler",
        severità: "INFO",
        messaggio: `Generatore: ${form.generator} — Tipo: ${form.type} — Art. 50(2)`,
        session_id: newAsset.id,
      },
      "trust-labeler"
    );
  }

  function exportManifestJSON(asset: LabeledAsset) {
    const blob = new Blob([JSON.stringify(asset.manifest, null, 2)], {
      type: "application/json",
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `c2pa-${asset.name.replace(/\s+/g, "-")}.json`;
    a.click();
    URL.revokeObjectURL(url);
    showToastMsg("Manifest JSON esportato");
  }

  function deleteAsset(id: string) {
    const updated = assets.filter((a) => a.id !== id);
    setAssets(updated);
    saveAssets(updated);
    if (selectedAsset?.id === id) setSelectedAsset(null);
    showToastMsg("Asset eliminato");
  }

  // ── Disclosure actions ──────────────────────────────────────────────────────

  function handleGenerateDisclosure() {
    const text = generateDisclosureText(disclosureForm);
    setDisclosureText(text);
  }

  function copyDisclosure() {
    if (!disclosureText) return;
    navigator.clipboard.writeText(disclosureText);
    showToastMsg("Testo copiato negli appunti");
  }

  function downloadDisclosure() {
    if (!disclosureText) return;
    const blob = new Blob([disclosureText], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `disclosure-art50-${disclosureForm.productName.replace(/\s+/g, "-") || "ai"}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    showToastMsg("File .txt scaricato");
  }

  function addDisclosureToEvidence() {
    if (!disclosureText) return;
    void appendEvidence(
      "log",
      {
        evento: "Disclosure Art. 50 generata",
        prodotto: disclosureForm.productName || "—",
        lingua: disclosureForm.language,
        caso_duso: disclosureForm.useCase,
        azienda: disclosureForm.companyName || "—",
        art_50_4: disclosureForm.deepfake ? "Sì" : "No",
        art_50_3: disclosureForm.emotionRecognition ? "Sì" : "No",
      },
      "trust-labeler"
    );
    showToastMsg("Aggiunto all'Evidence Layer ✓");
  }

  // ── Registry export ─────────────────────────────────────────────────────────

  function exportRegistryCSV() {
    const header = "nome,tipo,generatore,model_id,data,valido";
    const rows = assets.map((a) =>
      [
        `"${a.name}"`,
        a.type,
        `"${a.generator}"`,
        `"${a.modelId || ""}"`,
        a.labeledAt.slice(0, 10),
        a.verification.valid ? "true" : "false",
      ].join(",")
    );
    const csv = [header, ...rows].join("\n");
    const blob = new Blob([csv], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `trust-labeler-registry-${new Date().toISOString().slice(0, 10)}.csv`;
    a.click();
    URL.revokeObjectURL(url);
    showToastMsg("CSV esportato");
  }

  // ── Computed ────────────────────────────────────────────────────────────────

  const distinctTypes = new Set(assets.map((a) => a.type)).size;
  const lastLabeled = assets[0]?.labeledAt.slice(0, 10) ?? "—";

  // ── Render ───────────────────────────────────────────────────────────────────

  return (
    <div className="max-w-6xl">
      {/* Header */}
      <div className="mb-5">
        <h1
          style={{ fontSize: "22px", fontWeight: 400, letterSpacing: "-0.5px", color: "#0D1016" }}
        >
          Trust-Labeler
        </h1>
        <p className="text-[12px] mt-0.5" style={{ color: "rgba(0,0,0,0.42)" }}>
          Watermarking C2PA per contenuti AI generati. Disclosure obbligatorie.
        </p>
        <div className="flex gap-2 mt-2">
          {["Art. 50(1)", "Art. 50(2)", "Art. 50(4)"].map((art) => (
            <span
              key={art}
              className="text-[10px] rounded-full px-2 py-0.5"
              style={{ background: "rgba(0,0,0,0.06)", color: "rgba(0,0,0,0.45)" }}
            >
              {art}
            </span>
          ))}
        </div>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-3 gap-3 mb-5">
        {[
          { label: "Asset marcati", value: String(assets.length) },
          { label: "Tipi coperti", value: assets.length ? `${distinctTypes}/4` : "—" },
          { label: "Ultimo watermark", value: lastLabeled },
        ].map((card) => (
          <div
            key={card.label}
            className="rounded-xl p-4"
            style={{
              background: "#fff",
              border: "1px solid rgba(0,0,0,0.07)",
              boxShadow: "0 1px 3px rgba(0,0,0,0.04)",
            }}
          >
            <div
              className="text-[22px] font-semibold"
              style={{ letterSpacing: "-0.5px", color: "#0D1016" }}
            >
              {card.value}
            </div>
            <div className="mt-0.5 text-[11px]" style={{ color: "rgba(0,0,0,0.38)" }}>
              {card.label}
            </div>
          </div>
        ))}
      </div>

      {/* Tab nav */}
      <div
        className="flex gap-5 mb-5"
        style={{ borderBottom: "1px solid rgba(0,0,0,0.07)" }}
      >
        {[
          { id: "watermark" as const, label: "Watermarking C2PA", Icon: Stamp },
          { id: "disclosure" as const, label: "Disclosure Chatbot", Icon: MessageSquare },
          { id: "registry" as const, label: "Registro Asset", Icon: Archive },
        ].map(({ id, label, Icon }) => (
          <button
            key={id}
            onClick={() => setTab(id)}
            className="flex items-center gap-1.5 pb-3 text-[13px] font-medium transition-all border-b-2"
            style={
              tab === id
                ? { borderColor: "#0D1016", color: "#0D1016" }
                : { borderColor: "transparent", color: "rgba(0,0,0,0.42)" }
            }
          >
            <Icon className="h-3.5 w-3.5" />
            {label}
          </button>
        ))}
      </div>

      {/* ── TAB 1: Watermarking C2PA ── */}
      {tab === "watermark" && (
        <div className="grid lg:grid-cols-3 gap-5">
          {/* Left: list + form */}
          <div className="lg:col-span-2 space-y-4">
            {/* Asset list card */}
            <div
              className="rounded-xl overflow-hidden"
              style={{ border: "1px solid rgba(0,0,0,0.07)", background: "#fff" }}
            >
              <div
                className="flex items-center justify-between px-5 py-3.5"
                style={{ borderBottom: showForm || assets.length > 0 ? "1px solid rgba(0,0,0,0.06)" : "none" }}
              >
                <span className="text-[13px] font-medium" style={{ color: "#0D1016" }}>
                  Asset marcati
                </span>
                <button
                  onClick={() => setShowForm((v) => !v)}
                  className="flex items-center gap-1 text-[11px] font-semibold rounded-lg px-3 py-1.5"
                  style={{ background: "#0D1016", color: "#fff", border: "none", cursor: "pointer" }}
                >
                  {showForm ? <X className="h-3 w-3" /> : <Plus className="h-3 w-3" />}
                  {showForm ? "Annulla" : "Nuovo asset"}
                </button>
              </div>

              {assets.length === 0 && !showForm && (
                <div className="px-5 py-12 text-center">
                  <Stamp className="h-8 w-8 mx-auto mb-3" style={{ color: "rgba(0,0,0,0.15)" }} />
                  <p className="text-[13px] font-medium mb-1" style={{ color: "rgba(0,0,0,0.45)" }}>
                    Nessun asset watermarkato
                  </p>
                  <p className="text-[11px]" style={{ color: "rgba(0,0,0,0.3)" }}>
                    Aggiungi il primo contenuto AI generato.
                  </p>
                </div>
              )}

              {assets.length > 0 && (
                <div className="divide-y" style={{ borderColor: "rgba(0,0,0,0.05)" }}>
                  {assets.map((asset) => {
                    const Icon = TYPE_ICON[asset.type];
                    const color = TYPE_COLOR[asset.type];
                    const isSelected = selectedAsset?.id === asset.id;
                    return (
                      <div
                        key={asset.id}
                        onClick={() => setSelectedAsset(isSelected ? null : asset)}
                        className="px-5 py-3 cursor-pointer transition-colors hover:bg-gray-50"
                        style={{ background: isSelected ? "rgba(0,0,0,0.02)" : undefined }}
                      >
                        <div className="flex items-center justify-between">
                          <div className="flex items-center gap-2">
                            <Icon className="h-3.5 w-3.5 flex-shrink-0" style={{ color }} />
                            <span className="text-[12px] font-medium" style={{ color: "#0D1016" }}>
                              {asset.name}
                            </span>
                            <span
                              className="text-[10px] font-semibold rounded-full px-2 py-0.5"
                              style={{ background: `${color}18`, color }}
                            >
                              {TYPE_LABEL[asset.type]}
                            </span>
                          </div>
                          <span
                            className="text-[10px] font-semibold rounded-full px-2 py-0.5 flex items-center gap-1"
                            style={{ background: "rgba(22,163,74,0.08)", color: "#15803d" }}
                          >
                            <CheckCircle className="h-2.5 w-2.5" /> C2PA
                          </span>
                        </div>
                        <div className="flex items-center gap-3 mt-1 ml-5">
                          <span className="text-[10px]" style={{ color: "rgba(0,0,0,0.38)" }}>
                            {asset.generator}
                          </span>
                          <span className="text-[10px]" style={{ color: "rgba(0,0,0,0.28)" }}>
                            {asset.labeledAt.slice(0, 10)}
                          </span>
                        </div>
                      </div>
                    );
                  })}
                </div>
              )}
            </div>

            {/* Form */}
            <AnimatePresence>
              {showForm && (
                <motion.div
                  initial={{ opacity: 0, y: -8 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -8 }}
                  transition={{ duration: 0.15 }}
                  className="rounded-xl overflow-hidden"
                  style={{ border: "1px solid rgba(0,0,0,0.07)", background: "#fff" }}
                >
                  <div
                    className="px-5 py-3.5"
                    style={{ borderBottom: "1px solid rgba(0,0,0,0.06)" }}
                  >
                    <p className="text-[13px] font-medium" style={{ color: "#0D1016" }}>
                      Nuovo asset — Watermark C2PA
                    </p>
                  </div>
                  <div className="px-5 py-4 space-y-4">
                    {/* Name */}
                    <div>
                      <label
                        className="block text-[11px] font-medium mb-1"
                        style={{ color: "rgba(0,0,0,0.5)" }}
                      >
                        Nome file o identificativo <span style={{ color: "#dc2626" }}>*</span>
                      </label>
                      <input
                        style={INPUT_STYLE}
                        placeholder="Es. hero-banner.webp, campagna-ottobre.mp4"
                        value={form.name}
                        onChange={(e) => setForm((f) => ({ ...f, name: e.target.value }))}
                      />
                    </div>

                    {/* Type */}
                    <div>
                      <label
                        className="block text-[11px] font-medium mb-2"
                        style={{ color: "rgba(0,0,0,0.5)" }}
                      >
                        Tipo di contenuto
                      </label>
                      <div className="flex gap-2">
                        {(["image", "video", "audio", "text"] as AssetType[]).map((t) => {
                          const active = form.type === t;
                          return (
                            <button
                              key={t}
                              type="button"
                              onClick={() => setForm((f) => ({ ...f, type: t }))}
                              style={{
                                padding: "5px 12px",
                                borderRadius: "999px",
                                fontSize: "11px",
                                fontWeight: 500,
                                border: active
                                  ? `1px solid ${TYPE_COLOR[t]}`
                                  : "1px solid rgba(0,0,0,0.12)",
                                background: active ? `${TYPE_COLOR[t]}18` : "#fff",
                                color: active ? TYPE_COLOR[t] : "rgba(0,0,0,0.5)",
                                cursor: "pointer",
                                transition: "all 0.12s",
                              }}
                            >
                              {TYPE_LABEL[t]}
                            </button>
                          );
                        })}
                      </div>
                    </div>

                    {/* Generator */}
                    <div>
                      <label
                        className="block text-[11px] font-medium mb-1"
                        style={{ color: "rgba(0,0,0,0.5)" }}
                      >
                        AI generatore utilizzato <span style={{ color: "#dc2626" }}>*</span>
                      </label>
                      <select
                        style={{ ...INPUT_STYLE, cursor: "pointer" }}
                        value={form.generator}
                        onChange={(e) =>
                          setForm((f) => ({ ...f, generator: e.target.value as AI_GENERATOR }))
                        }
                      >
                        {AI_GENERATORS.map((g) => (
                          <option key={g} value={g}>
                            {g}
                          </option>
                        ))}
                      </select>
                    </div>

                    {/* Model ID */}
                    <div>
                      <label
                        className="block text-[11px] font-medium mb-1"
                        style={{ color: "rgba(0,0,0,0.5)" }}
                      >
                        Model ID / versione{" "}
                        <span style={{ color: "rgba(0,0,0,0.3)", fontSize: "10px" }}>
                          (opzionale)
                        </span>
                      </label>
                      <input
                        style={INPUT_STYLE}
                        placeholder="Es. gpt-4o-2024-11, midjourney-v6.1"
                        value={form.modelId}
                        onChange={(e) => setForm((f) => ({ ...f, modelId: e.target.value }))}
                      />
                    </div>

                    <button
                      onClick={handleGenerateWatermark}
                      disabled={!form.name.trim()}
                      style={{
                        width: "100%",
                        padding: "9px",
                        borderRadius: "8px",
                        fontSize: "13px",
                        fontWeight: 600,
                        background: form.name.trim() ? "#0D1016" : "rgba(0,0,0,0.1)",
                        color: form.name.trim() ? "#fff" : "rgba(0,0,0,0.3)",
                        border: "none",
                        cursor: form.name.trim() ? "pointer" : "not-allowed",
                      }}
                    >
                      Genera watermark C2PA
                    </button>
                  </div>
                </motion.div>
              )}
            </AnimatePresence>
          </div>

          {/* Right: detail */}
          <div className="lg:col-span-1 space-y-4">
            {!selectedAsset ? (
              <div
                className="rounded-xl p-6 text-center"
                style={{ border: "1px solid rgba(0,0,0,0.07)", background: "#fff" }}
              >
                <Shield
                  className="h-8 w-8 mx-auto mb-3"
                  style={{ color: "rgba(0,0,0,0.15)" }}
                />
                <p className="text-[12px]" style={{ color: "rgba(0,0,0,0.4)" }}>
                  Seleziona un asset per vedere i dettagli del manifest C2PA.
                </p>
              </div>
            ) : (
              <>
                {/* Card 1: Metadata */}
                <div
                  className="rounded-xl overflow-hidden"
                  style={{ border: "1px solid rgba(0,0,0,0.07)", background: "#fff" }}
                >
                  <div
                    className="px-4 py-3"
                    style={{ borderBottom: "1px solid rgba(0,0,0,0.06)" }}
                  >
                    <p
                      className="text-[12px] font-medium truncate"
                      style={{ color: "#0D1016" }}
                    >
                      {selectedAsset.name}
                    </p>
                  </div>
                  <div className="px-4 py-3 space-y-2">
                    {[
                      { label: "Algoritmo", value: selectedAsset.manifest.alg },
                      {
                        label: "Generatore",
                        value: String(
                          selectedAsset.manifest.assertions[0].data.generator ?? "—"
                        ),
                      },
                      { label: "Model ID", value: selectedAsset.modelId || "—" },
                      {
                        label: "Timestamp",
                        value: selectedAsset.manifest.iat
                          .slice(0, 19)
                          .replace("T", " "),
                      },
                      {
                        label: "Certificato",
                        value: `X.509 — ${selectedAsset.manifest.credentials[0].issuer}`,
                      },
                      {
                        label: "Firma",
                        value: selectedAsset.manifest.signature.slice(0, 28) + "...",
                      },
                      { label: "Giurisdizione", value: "EU — Art. 50(2)" },
                    ].map((row) => (
                      <div
                        key={row.label}
                        className="flex justify-between text-[11px] py-1"
                        style={{ borderBottom: "1px solid rgba(0,0,0,0.04)" }}
                      >
                        <span style={{ color: "rgba(0,0,0,0.42)" }}>{row.label}</span>
                        <span
                          className="font-mono text-right max-w-[160px] truncate"
                          style={{ color: "#0D1016", fontSize: "10px" }}
                        >
                          {row.value}
                        </span>
                      </div>
                    ))}
                  </div>
                  <div
                    className="px-4 py-3 flex flex-col gap-2"
                    style={{ borderTop: "1px solid rgba(0,0,0,0.06)" }}
                  >
                    <button
                      onClick={() => exportManifestJSON(selectedAsset)}
                      className="flex items-center justify-center gap-1.5 w-full text-[11px] font-medium rounded-lg px-3 py-2 hover:opacity-80 transition-opacity"
                      style={{ border: "1px solid rgba(0,0,0,0.1)", color: "rgba(0,0,0,0.6)" }}
                    >
                      <Download className="h-3 w-3" /> Esporta manifest JSON
                    </button>
                    <button
                      onClick={() => deleteAsset(selectedAsset.id)}
                      className="text-[11px] text-center hover:opacity-70 transition-opacity"
                      style={{ color: "#dc2626", background: "none", border: "none", cursor: "pointer" }}
                    >
                      Elimina asset
                    </button>
                  </div>
                </div>

                {/* Card 2: Verification */}
                <div
                  className="rounded-xl overflow-hidden"
                  style={{ border: "1px solid rgba(0,0,0,0.07)", background: "#fff" }}
                >
                  <div
                    className="px-4 py-3"
                    style={{ borderBottom: "1px solid rgba(0,0,0,0.06)" }}
                  >
                    <p className="text-[12px] font-medium" style={{ color: "#0D1016" }}>
                      Verifica crittografica
                    </p>
                  </div>
                  <div className="px-4 py-3 space-y-2">
                    {selectedAsset.verification.checks.map((check, i) => (
                      <div
                        key={i}
                        className="flex items-start gap-2 text-[11px]"
                      >
                        {check.passed ? (
                          <CheckCircle
                            className="h-3.5 w-3.5 flex-shrink-0 mt-0.5"
                            style={{ color: "#15803d" }}
                          />
                        ) : (
                          <X
                            className="h-3.5 w-3.5 flex-shrink-0 mt-0.5"
                            style={{ color: "#dc2626" }}
                          />
                        )}
                        <div>
                          <span
                            style={{
                              color: check.passed ? "#15803d" : "#dc2626",
                              fontWeight: 500,
                            }}
                          >
                            {check.name}
                          </span>
                          <span
                            className="block text-[10px]"
                            style={{ color: "rgba(0,0,0,0.4)" }}
                          >
                            {check.detail}
                          </span>
                        </div>
                      </div>
                    ))}
                  </div>
                  <div
                    className="px-4 py-2.5"
                    style={{ borderTop: "1px solid rgba(0,0,0,0.06)" }}
                  >
                    {selectedAsset.verification.valid ? (
                      <p
                        className="text-[11px] font-medium flex items-center gap-1"
                        style={{ color: "#15803d" }}
                      >
                        <CheckCircle className="h-3 w-3" /> Manifest C2PA valido
                      </p>
                    ) : (
                      <p
                        className="text-[11px] font-medium flex items-center gap-1"
                        style={{ color: "#dc2626" }}
                      >
                        <AlertTriangle className="h-3 w-3" /> Verifica fallita
                      </p>
                    )}
                  </div>
                </div>

                {/* Card 3: Compliance badge */}
                <div
                  className="rounded-xl p-4 text-center"
                  style={{
                    background: "rgba(59,130,246,0.04)",
                    border: "1px solid rgba(59,130,246,0.15)",
                  }}
                >
                  <Shield
                    className="h-8 w-8 mx-auto mb-2"
                    style={{ color: "#3b82f6" }}
                  />
                  <p
                    className="text-[12px] font-semibold mb-0.5"
                    style={{ color: "#0D1016" }}
                  >
                    AI-Generated Content
                  </p>
                  <p className="text-[10px] mb-2" style={{ color: "rgba(0,0,0,0.45)" }}>
                    Conforme Art. 50(2) — C2PA v2.1
                  </p>
                  <p className="text-[10px] mb-0.5" style={{ color: "rgba(0,0,0,0.5)" }}>
                    Generatore: {selectedAsset.generator}
                  </p>
                  <p className="text-[10px] mb-3" style={{ color: "rgba(0,0,0,0.35)" }}>
                    Data: {selectedAsset.labeledAt.slice(0, 10)}
                  </p>
                  <div
                    className="text-[10px] space-y-1"
                    style={{ color: "rgba(0,0,0,0.45)" }}
                  >
                    {[
                      { name: "LinkedIn", ok: true },
                      { name: "Google Search", ok: true },
                      { name: "Meta", ok: true },
                      { name: "X/Twitter", ok: false },
                      { name: "TikTok", ok: false },
                    ].map((p) => (
                      <div key={p.name} className="flex items-center justify-between">
                        <span>{p.name}</span>
                        <span style={{ color: p.ok ? "#15803d" : "rgba(0,0,0,0.3)" }}>
                          {p.ok ? "✓" : "In attesa"}
                        </span>
                      </div>
                    ))}
                  </div>
                </div>
              </>
            )}
          </div>
        </div>
      )}

      {/* ── TAB 2: Disclosure Chatbot ── */}
      {tab === "disclosure" && (
        <div className="max-w-2xl space-y-5">
          {/* Banner */}
          <div
            className="rounded-xl p-4"
            style={{ background: "rgba(59,130,246,0.04)", border: "1px solid rgba(59,130,246,0.15)" }}
          >
            <p className="text-[11px] leading-relaxed" style={{ color: "rgba(0,0,0,0.55)" }}>
              <span className="font-semibold" style={{ color: "#1d4ed8" }}>
                Art. 50(1) AIA —{" "}
              </span>
              I sistemi AI che interagiscono con persone fisiche devono informarle in modo chiaro e
              comprensibile che stanno interagendo con un AI, salvo che sia evidente dal contesto.{" "}
              <span className="font-semibold" style={{ color: "#1d4ed8" }}>Art. 50(3) —</span>{" "}
              Obblighi per emotion recognition e categorizzazione biometrica.{" "}
              <span className="font-semibold" style={{ color: "#1d4ed8" }}>Art. 50(4) —</span>{" "}
              Obbligo di disclosure per deep fake e contenuti sintetici.
            </p>
          </div>

          {/* Form */}
          <div
            className="rounded-xl overflow-hidden"
            style={{ border: "1px solid rgba(0,0,0,0.07)", background: "#fff" }}
          >
            <div className="px-5 py-3.5" style={{ borderBottom: "1px solid rgba(0,0,0,0.06)" }}>
              <p className="text-[13px] font-medium" style={{ color: "#0D1016" }}>
                Genera testo disclosure
              </p>
            </div>
            <div className="px-5 py-4 space-y-4">
              {/* Product name */}
              <div>
                <label
                  className="block text-[11px] font-medium mb-1"
                  style={{ color: "rgba(0,0,0,0.5)" }}
                >
                  Nome prodotto / sistema
                </label>
                <input
                  style={INPUT_STYLE}
                  placeholder="Es. Assistente Virtuale Banca XYZ, Chatbot HR"
                  value={disclosureForm.productName}
                  onChange={(e) =>
                    setDisclosureForm((f) => ({ ...f, productName: e.target.value }))
                  }
                />
              </div>

              {/* Use case */}
              <div>
                <label
                  className="block text-[11px] font-medium mb-1"
                  style={{ color: "rgba(0,0,0,0.5)" }}
                >
                  Caso d&apos;uso
                </label>
                <select
                  style={{ ...INPUT_STYLE, cursor: "pointer" }}
                  value={disclosureForm.useCase}
                  onChange={(e) =>
                    setDisclosureForm((f) => ({ ...f, useCase: e.target.value }))
                  }
                >
                  <option value="chatbot_customer_support">Chatbot assistenza clienti</option>
                  <option value="chatbot_hr">Chatbot HR / recruiting</option>
                  <option value="chatbot_legal">Assistente legale AI</option>
                  <option value="chatbot_medical">Assistente medico / salute</option>
                  <option value="content_generation">
                    Generazione contenuti (testi, immagini)
                  </option>
                  <option value="recommendation">Sistema di raccomandazione</option>
                  <option value="deepfake">Contenuti sintetici / deepfake</option>
                  <option value="emotion_recognition">Riconoscimento emozioni</option>
                </select>
              </div>

              {/* Company */}
              <div>
                <label
                  className="block text-[11px] font-medium mb-1"
                  style={{ color: "rgba(0,0,0,0.5)" }}
                >
                  Nome azienda
                </label>
                <input
                  style={INPUT_STYLE}
                  placeholder="Es. Acme S.p.A."
                  value={disclosureForm.companyName}
                  onChange={(e) =>
                    setDisclosureForm((f) => ({ ...f, companyName: e.target.value }))
                  }
                />
              </div>

              {/* Language */}
              <div>
                <label
                  className="block text-[11px] font-medium mb-2"
                  style={{ color: "rgba(0,0,0,0.5)" }}
                >
                  Lingua testo disclosure
                </label>
                <div className="flex gap-2">
                  {(["it", "en"] as const).map((lang) => {
                    const active = disclosureForm.language === lang;
                    return (
                      <button
                        key={lang}
                        type="button"
                        onClick={() => setDisclosureForm((f) => ({ ...f, language: lang }))}
                        style={{
                          padding: "5px 14px",
                          borderRadius: "999px",
                          fontSize: "12px",
                          fontWeight: 500,
                          border: active ? "1px solid #0D1016" : "1px solid rgba(0,0,0,0.12)",
                          background: active ? "#0D1016" : "#fff",
                          color: active ? "#fff" : "rgba(0,0,0,0.5)",
                          cursor: "pointer",
                        }}
                      >
                        {lang === "it" ? "🇮🇹 Italiano" : "🇬🇧 English"}
                      </button>
                    );
                  })}
                </div>
              </div>

              {/* Checkboxes */}
              <div className="space-y-2">
                {[
                  {
                    key: "deepfake" as const,
                    label: "Includi obbligo deepfake Art. 50(4)",
                  },
                  {
                    key: "emotionRecognition" as const,
                    label: "Includi obbligo emotion recognition Art. 50(3)",
                  },
                ].map(({ key, label }) => (
                  <label
                    key={key}
                    className="flex items-center gap-2 cursor-pointer"
                    style={{ fontSize: "12px", color: "rgba(0,0,0,0.6)" }}
                  >
                    <input
                      type="checkbox"
                      checked={disclosureForm[key]}
                      onChange={(e) =>
                        setDisclosureForm((f) => ({ ...f, [key]: e.target.checked }))
                      }
                      className="rounded"
                    />
                    {label}
                  </label>
                ))}
              </div>

              <button
                onClick={handleGenerateDisclosure}
                style={{
                  width: "100%",
                  padding: "9px",
                  borderRadius: "8px",
                  fontSize: "13px",
                  fontWeight: 600,
                  background: "#0D1016",
                  color: "#fff",
                  border: "none",
                  cursor: "pointer",
                }}
              >
                Genera testo disclosure
              </button>
            </div>
          </div>

          {/* Output */}
          <AnimatePresence>
            {disclosureText && (
              <motion.div
                initial={{ opacity: 0, y: -6 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0 }}
                transition={{ duration: 0.15 }}
                className="rounded-xl overflow-hidden"
                style={{ border: "1px solid rgba(22,163,74,0.25)", background: "#fff" }}
              >
                <div
                  className="flex items-center justify-between px-5 py-3.5"
                  style={{ borderBottom: "1px solid rgba(0,0,0,0.06)" }}
                >
                  <p className="text-[13px] font-medium" style={{ color: "#0D1016" }}>
                    Testo disclosure generato
                  </p>
                  <div className="flex gap-2">
                    <button
                      onClick={copyDisclosure}
                      className="flex items-center gap-1 text-[11px] font-medium rounded-lg px-2.5 py-1.5 hover:opacity-80 transition-opacity"
                      style={{ border: "1px solid rgba(0,0,0,0.1)", color: "rgba(0,0,0,0.6)" }}
                    >
                      <Copy className="h-3 w-3" /> Copia
                    </button>
                    <button
                      onClick={downloadDisclosure}
                      className="flex items-center gap-1 text-[11px] font-medium rounded-lg px-2.5 py-1.5 hover:opacity-80 transition-opacity"
                      style={{ border: "1px solid rgba(0,0,0,0.1)", color: "rgba(0,0,0,0.6)" }}
                    >
                      <Download className="h-3 w-3" /> .txt
                    </button>
                    <button
                      onClick={addDisclosureToEvidence}
                      className="flex items-center gap-1 text-[11px] font-semibold rounded-lg px-2.5 py-1.5 hover:opacity-80 transition-opacity"
                      style={{ background: "#0D1016", color: "#fff", border: "none", cursor: "pointer" }}
                    >
                      + Evidence Layer
                    </button>
                  </div>
                </div>
                <div className="px-5 py-4">
                  <textarea
                    readOnly
                    value={disclosureText}
                    className="w-full rounded-lg text-[11px] font-mono p-3 focus:outline-none resize-none"
                    rows={10}
                    style={{
                      background: "rgba(0,0,0,0.02)",
                      border: "1px solid rgba(22,163,74,0.2)",
                      color: "#0D1016",
                      lineHeight: 1.6,
                    }}
                  />
                </div>

                {/* Implementation checklist */}
                <div
                  className="px-5 pb-4"
                >
                  <div
                    className="rounded-lg p-4"
                    style={{ background: "rgba(0,0,0,0.02)", border: "1px solid rgba(0,0,0,0.06)" }}
                  >
                    <p
                      className="text-[11px] font-semibold mb-2"
                      style={{ color: "rgba(0,0,0,0.55)" }}
                    >
                      Come usare questa disclosure:
                    </p>
                    {[
                      "Inseriscila come primo messaggio nella chat di benvenuto",
                      "Aggiungila al footer del prodotto AI",
                      "Includila nell'informativa privacy",
                      "Verifica che sia visibile prima di qualsiasi interazione AI",
                    ].map((item) => (
                      <div key={item} className="flex items-start gap-2 mb-1.5">
                        <CheckCircle
                          className="h-3 w-3 flex-shrink-0 mt-0.5"
                          style={{ color: "#15803d" }}
                        />
                        <span className="text-[11px]" style={{ color: "rgba(0,0,0,0.55)" }}>
                          {item}
                        </span>
                      </div>
                    ))}
                  </div>
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      )}

      {/* ── TAB 3: Registro Asset ── */}
      {tab === "registry" && (
        <div className="space-y-5">
          {/* Stats */}
          <div className="grid grid-cols-4 gap-3">
            {[
              { label: "Totale", value: assets.length },
              { label: "Immagini", value: assets.filter((a) => a.type === "image").length },
              {
                label: "Video + Audio",
                value:
                  assets.filter((a) => a.type === "video").length +
                  assets.filter((a) => a.type === "audio").length,
              },
              { label: "Testi", value: assets.filter((a) => a.type === "text").length },
            ].map((stat) => (
              <div
                key={stat.label}
                className="rounded-xl p-4"
                style={{
                  background: "#fff",
                  border: "1px solid rgba(0,0,0,0.07)",
                  boxShadow: "0 1px 3px rgba(0,0,0,0.04)",
                }}
              >
                <div
                  className="text-[22px] font-semibold"
                  style={{ letterSpacing: "-0.5px", color: "#0D1016" }}
                >
                  {stat.value}
                </div>
                <div className="mt-0.5 text-[11px]" style={{ color: "rgba(0,0,0,0.38)" }}>
                  {stat.label}
                </div>
              </div>
            ))}
          </div>

          {/* Table */}
          <div
            className="rounded-xl overflow-hidden"
            style={{ border: "1px solid rgba(0,0,0,0.07)", background: "#fff" }}
          >
            <div
              className="flex items-center justify-between px-5 py-3.5"
              style={{ borderBottom: "1px solid rgba(0,0,0,0.06)" }}
            >
              <p className="text-[13px] font-medium" style={{ color: "#0D1016" }}>
                Tutti gli asset marcati
              </p>
              {assets.length > 0 && (
                <button
                  onClick={exportRegistryCSV}
                  className="flex items-center gap-1 text-[11px] font-medium rounded-lg px-3 py-1.5 hover:opacity-80 transition-opacity"
                  style={{ border: "1px solid rgba(0,0,0,0.1)", color: "rgba(0,0,0,0.6)" }}
                >
                  <Download className="h-3 w-3" /> Esporta tutto (CSV)
                </button>
              )}
            </div>

            {assets.length === 0 ? (
              <div className="px-5 py-12 text-center">
                <Archive
                  className="h-8 w-8 mx-auto mb-3"
                  style={{ color: "rgba(0,0,0,0.15)" }}
                />
                <p className="text-[13px] font-medium mb-1" style={{ color: "rgba(0,0,0,0.45)" }}>
                  Nessun asset nel registro
                </p>
                <p className="text-[11px]" style={{ color: "rgba(0,0,0,0.3)" }}>
                  Vai al tab Watermarking per aggiungere il primo.
                </p>
              </div>
            ) : (
              <div className="overflow-x-auto">
                <table className="w-full">
                  <thead>
                    <tr style={{ borderBottom: "1px solid rgba(0,0,0,0.06)" }}>
                      {["Nome", "Tipo", "Generatore", "Model ID", "Data", "Verifica", "Azioni"].map(
                        (col) => (
                          <th
                            key={col}
                            className="px-4 py-2.5 text-left text-[10px] font-semibold uppercase tracking-wide"
                            style={{ color: "rgba(0,0,0,0.35)" }}
                          >
                            {col}
                          </th>
                        )
                      )}
                    </tr>
                  </thead>
                  <tbody>
                    {assets.map((asset) => {
                      const Icon = TYPE_ICON[asset.type];
                      const color = TYPE_COLOR[asset.type];
                      return (
                        <tr
                          key={asset.id}
                          className="hover:bg-gray-50 transition-colors"
                          style={{ borderBottom: "1px solid rgba(0,0,0,0.04)" }}
                        >
                          <td className="px-4 py-2.5">
                            <div className="flex items-center gap-1.5">
                              <Icon className="h-3.5 w-3.5 flex-shrink-0" style={{ color }} />
                              <span
                                className="text-[12px] font-medium max-w-[140px] truncate"
                                style={{ color: "#0D1016" }}
                              >
                                {asset.name}
                              </span>
                            </div>
                          </td>
                          <td className="px-4 py-2.5">
                            <span
                              className="text-[10px] font-semibold rounded-full px-2 py-0.5"
                              style={{ background: `${color}18`, color }}
                            >
                              {TYPE_LABEL[asset.type]}
                            </span>
                          </td>
                          <td className="px-4 py-2.5 text-[11px]" style={{ color: "rgba(0,0,0,0.55)", maxWidth: "160px" }}>
                            <span className="truncate block">{asset.generator}</span>
                          </td>
                          <td
                            className="px-4 py-2.5 text-[11px] font-mono"
                            style={{ color: "rgba(0,0,0,0.4)" }}
                          >
                            {asset.modelId || "—"}
                          </td>
                          <td
                            className="px-4 py-2.5 text-[11px]"
                            style={{ color: "rgba(0,0,0,0.45)" }}
                          >
                            {asset.labeledAt.slice(0, 10)}
                          </td>
                          <td className="px-4 py-2.5">
                            {asset.verification.valid ? (
                              <span
                                className="text-[10px] font-medium flex items-center gap-1"
                                style={{ color: "#15803d" }}
                              >
                                <CheckCircle className="h-3 w-3" /> Valido
                              </span>
                            ) : (
                              <span
                                className="text-[10px] font-medium flex items-center gap-1"
                                style={{ color: "#dc2626" }}
                              >
                                <AlertTriangle className="h-3 w-3" /> Errore
                              </span>
                            )}
                          </td>
                          <td className="px-4 py-2.5">
                            <div className="flex items-center gap-2">
                              <button
                                onClick={() => exportManifestJSON(asset)}
                                className="text-[10px] font-medium hover:opacity-70 transition-opacity flex items-center gap-0.5"
                                style={{ color: "rgba(0,0,0,0.5)", background: "none", border: "none", cursor: "pointer" }}
                              >
                                <Download className="h-3 w-3" /> JSON
                              </button>
                              <button
                                onClick={() => deleteAsset(asset.id)}
                                className="text-[10px] font-medium hover:opacity-70 transition-opacity"
                                style={{ color: "#dc2626", background: "none", border: "none", cursor: "pointer" }}
                              >
                                Elimina
                              </button>
                            </div>
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Toast */}
      {toast && (
        <div
          className="fixed bottom-6 right-6 z-50 rounded-xl px-4 py-3 text-sm font-medium shadow-lg"
          style={{ background: "#0D1016", color: "#fff" }}
        >
          {toast}
        </div>
      )}
    </div>
  );
}
