"use client";

// Component 3 — AI Output Label
// Header for every AI-generated card/block.
// Shows: badges, doc type, model, output ID, timestamp, system version.

import { Bot, Scale, Calendar, Cpu, Hash, Info } from "lucide-react";
import { getAIModelName, getSystemVersion } from "@/lib/disclosure/ai-config";
import { generateOutputId } from "@/lib/disclosure/output-id";
import type { OutputType } from "@/lib/disclosure/output-id";
import { useState, useEffect } from "react";

const copy = {
  it: {
    badge: "Generato da AI",
    review: "Richiede revisione legale",
    tipo: "Tipo",
    modello: "Modello",
    id: "ID Output",
    versione: "Versione",
    generatedAt: "Generato il",
  },
  en: {
    badge: "Generated by AI",
    review: "Requires legal review",
    tipo: "Type",
    modello: "Model",
    id: "Output ID",
    versione: "Version",
    generatedAt: "Generated",
  },
};

interface AIOutputLabelProps {
  documentType: string;     // es. "Documentazione Tecnica Art. 11"
  outputType: OutputType;   // es. "AIA", "RSK" — used for ID generation
  lang?: "it" | "en";
  /** If provided, uses this ID instead of generating a new one (for display of existing outputs) */
  existingId?: string;
  /** If provided, uses this timestamp */
  generatedAt?: string;
  /** Show/hide the bottom border separator */
  separator?: boolean;
}

export default function AIOutputLabel({
  documentType,
  outputType,
  lang = "it",
  existingId,
  generatedAt,
  separator = true,
}: AIOutputLabelProps) {
  const t = copy[lang];
  const modelName = getAIModelName();
  const version = getSystemVersion();

  const [outputId, setOutputId] = useState<string>(existingId ?? "");
  const [timestamp, setTimestamp] = useState<string>("");

  useEffect(() => {
    if (!existingId) {
      setOutputId(generateOutputId(outputType));
    }
    const dt = generatedAt ? new Date(generatedAt) : new Date();
    setTimestamp(
      dt.toLocaleString(lang === "it" ? "it-IT" : "en-GB", {
        day: "2-digit",
        month: "2-digit",
        year: "numeric",
        hour: "2-digit",
        minute: "2-digit",
      })
    );
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <div
      className="rounded-t-xl px-4 py-3"
      style={{
        background: "#F0F7FF",
        border: "1px solid #B8D4F0",
        borderBottom: separator ? "1px solid #B8D4F0" : "none",
      }}
    >
      {/* Row 1: badges + doc type */}
      <div className="flex items-center gap-2 flex-wrap mb-1.5">
        {/* Generated by AI badge */}
        <span
          className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold"
          style={{ background: "#0C447C", color: "#ffffff" }}
        >
          <Bot size={9} strokeWidth={2} />
          {t.badge}
        </span>

        {/* Document type */}
        <span
          className="text-[11px] font-medium"
          style={{ color: "#0C447C" }}
        >
          {documentType}
        </span>

        {/* Requires legal review badge */}
        <span
          className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold ml-auto"
          style={{ background: "#FEF3C7", color: "#92400E", border: "1px solid #FDE68A" }}
        >
          <Scale size={9} strokeWidth={2} />
          {t.review}
        </span>
      </div>

      {/* Row 2: metadata */}
      <div className="flex items-center gap-3 flex-wrap">
        {/* Timestamp */}
        <span className="inline-flex items-center gap-1 text-[10px]" style={{ color: "#4A7AA8" }}>
          <Calendar size={9} strokeWidth={2} />
          {timestamp}
        </span>

        <span style={{ color: "#B8D4F0" }}>·</span>

        {/* Model */}
        <span className="inline-flex items-center gap-1 text-[10px]" style={{ color: "#4A7AA8" }}>
          <Cpu size={9} strokeWidth={2} />
          {modelName}
        </span>

        <span style={{ color: "#B8D4F0" }}>·</span>

        {/* Output ID */}
        <span className="inline-flex items-center gap-1 text-[10px] font-mono" style={{ color: "#4A7AA8" }}>
          <Hash size={9} strokeWidth={2} />
          {outputId || "—"}
        </span>

        <span style={{ color: "#B8D4F0" }}>·</span>

        {/* Version */}
        <span className="inline-flex items-center gap-1 text-[10px]" style={{ color: "#4A7AA8" }}>
          <Info size={9} strokeWidth={2} />
          v{version}
        </span>
      </div>
    </div>
  );
}
