"use client";

// Component 1 — Art. 50 Disclosure Modal
// Shown once per user on first authenticated session.
// Blocking: cannot be closed without clicking the CTA.

import { useState, useEffect } from "react";
import { Shield } from "lucide-react";

const STORAGE_KEY = "aicomply_disclosure_acknowledged";

const copy = {
  it: {
    title: "Informativa sull'uso dell'Intelligenza Artificiale",
    body: [
      "AIComply utilizza sistemi di intelligenza artificiale per assisterti nella redazione di documentazione di compliance ai sensi del Regolamento UE 2024/1689 (AI Act).",
      "Prima di procedere, è importante che tu sappia:",
    ],
    bullets: [
      "Tutti i contenuti generati o analizzati dall'AI sono contrassegnati con badge \"Generato da AI\"",
      "I documenti prodotti richiedono revisione legale da parte di un professionista qualificato prima di qualsiasi uso ufficiale",
      "AIComply non sostituisce la consulenza legale: i suoi output sono strumenti di supporto, non pareri professionali",
      "Ogni output è tracciato con un ID univoco per garantire l'audit trail ai sensi dell'Art. 50 e dell'Art. 12 del Regolamento UE 2024/1689",
      "Il modello AI utilizzato è indicato su ogni output; le citazioni normative sono marcate per verifica puntuale",
    ],
    cta: "Ho compreso — continua",
    link: "Leggi l'informativa completa sulla trasparenza AI →",
    badge: "Art. 50 — Reg. UE 2024/1689",
  },
  en: {
    title: "AI System Disclosure Notice",
    body: [
      "AIComply uses artificial intelligence systems to assist you in drafting compliance documentation under Regulation (EU) 2024/1689 (AI Act).",
      "Before proceeding, please be aware:",
    ],
    bullets: [
      "All content generated or analysed by AI is labelled with a \"Generated by AI\" badge",
      "Documents produced require legal review by a qualified professional before any official use",
      "AIComply does not replace legal advice: its outputs are support tools, not professional opinions",
      "Each output is tracked with a unique ID to ensure the audit trail required under Art. 50 and Art. 12 of Regulation (EU) 2024/1689",
      "The AI model used is shown on every output; regulatory citations are marked for point-by-point verification",
    ],
    cta: "I understand — continue",
    link: "Read the full AI transparency notice →",
    badge: "Art. 50 — Reg. (EU) 2024/1689",
  },
};

interface DisclosureModalProps {
  lang?: "it" | "en";
}

export default function DisclosureModal({ lang = "it" }: DisclosureModalProps) {
  const [visible, setVisible] = useState(false);
  const t = copy[lang];

  useEffect(() => {
    if (typeof window === "undefined") return;
    const ack = localStorage.getItem(STORAGE_KEY);
    if (!ack) setVisible(true);
  }, []);

  function handleAcknowledge() {
    if (typeof window !== "undefined") {
      localStorage.setItem(STORAGE_KEY, "true");
    }
    setVisible(false);
  }

  if (!visible) return null;

  return (
    <div
      className="fixed inset-0 z-[9999] flex items-center justify-center"
      style={{ background: "rgba(0,0,0,0.72)" }}
      // Intentionally NOT closing on backdrop click — modal is blocking
    >
      <div
        className="relative w-full max-w-lg mx-4 rounded-2xl overflow-hidden"
        style={{
          background: "#ffffff",
          boxShadow: "0 32px 80px rgba(0,0,0,0.35)",
        }}
      >
        {/* Top accent bar */}
        <div style={{ height: 4, background: "linear-gradient(90deg, #0C447C, #3b82f6)" }} />

        <div className="px-8 py-7">
          {/* Icon + badge */}
          <div className="flex items-center justify-between mb-5">
            <div
              className="flex items-center justify-center rounded-xl"
              style={{ width: 44, height: 44, background: "#E6F1FB" }}
            >
              <Shield size={22} style={{ color: "#0C447C" }} strokeWidth={1.5} />
            </div>
            <span
              className="text-[10px] font-semibold px-2.5 py-1 rounded-full"
              style={{ background: "#E6F1FB", color: "#0C447C", letterSpacing: "0.5px" }}
            >
              {t.badge}
            </span>
          </div>

          {/* Title */}
          <h2
            className="mb-4"
            style={{ fontSize: "17px", fontWeight: 600, color: "#0D1016", letterSpacing: "-0.4px", lineHeight: 1.3 }}
          >
            {t.title}
          </h2>

          {/* Body */}
          <p className="text-[13px] mb-3" style={{ color: "rgba(0,0,0,0.55)", lineHeight: 1.6 }}>
            {t.body[0]}
          </p>
          <p className="text-[12px] font-semibold mb-2" style={{ color: "#0D1016" }}>
            {t.body[1]}
          </p>

          {/* Bullets */}
          <ul className="mb-6 space-y-2">
            {t.bullets.map((b, i) => (
              <li key={i} className="flex items-start gap-2 text-[12px]" style={{ color: "rgba(0,0,0,0.6)", lineHeight: 1.5 }}>
                <span className="mt-1 flex-shrink-0 rounded-full" style={{ width: 5, height: 5, background: "#3b82f6", marginTop: 6 }} />
                {b}
              </li>
            ))}
          </ul>

          {/* CTA */}
          <button
            onClick={handleAcknowledge}
            className="w-full py-3 rounded-xl text-[13px] font-semibold transition-all hover:opacity-90 active:scale-[0.98]"
            style={{ background: "#0D1016", color: "#ffffff", border: "none", cursor: "pointer" }}
          >
            {t.cta}
          </button>

          {/* Secondary link */}
          <div className="mt-3 text-center">
            <a
              href="/legal/ai-disclosure"
              className="text-[11px] transition-opacity hover:opacity-70"
              style={{ color: "#3b82f6" }}
            >
              {t.link}
            </a>
          </div>
        </div>
      </div>
    </div>
  );
}
